### ISSUE TITLE
Widget not showing anything

### ISSUE THREAD

**Issue by IDEAGroupe** [Centreon-Widgets/centreon-widget-live-top10-memory-usage#3]
Hi,

Recently install a new CES 3.3 standard and come to the widget-live-top10-memory-usage, add it to the dashboard with some memory services add to my hosts ... nothing showing on the widget.

the cpu widget work like a charm.

![2016-04-01 14_46_37-centwidg](https://cloud.githubusercontent.com/assets/18213090/14207172/a2d3bfae-f818-11e5-92eb-eea7d1d2d913.png)

![image](https://cloud.githubusercontent.com/assets/18213090/14207179/b4b71220-f818-11e5-9377-ae996d116e87.png)

![image](https://cloud.githubusercontent.com/assets/18213090/14207184/c1cd13ce-f818-11e5-8cff-822b5d2efac6.png)

**Comment by julienmathis** [comment]
Do you select a hostgroup ?

**Comment by IDEAGroupe** [comment]
I try with and without a hostgroup same thing

**Comment by IDEAGroupe** [comment]
Find some log in error.log from apache

_```
[Mon Apr 04 10:01:42 2016] [error] [client 10.29.0.118] PHP Warning:  strlen() expects parameter 1 to be string, array given in /usr/share/centreon/www/lib/HTML/QuickForm/checkbox.php on line 126, referer: http://srv-ces/centreon/
[Mon Apr 04 10:01:45 2016] [error] [client 10.29.0.118] PHP Notice:  Undefined index: autoRefresh in /usr/share/centreon/www/widgets/tactical-overview/src/hosts_status.php on line 82, referer: http://srv-ces/centreon/main.php?
[Mon Apr 04 10:01:46 2016] [error] [client 10.29.0.118] PHP Notice:  Undefined index: autoRefresh in /usr/share/centreon/www/widgets/tactical-overview/src/services_status.php on line 99, referer: http://srv-ces/centreon/main.php?
[Mon Apr 04 10:01:46 2016] [error] [client 10.29.0.118] PHP Notice:  Undefined index: autoRefresh in /usr/share/centreon/www/widgets/live-top10-cpu-usage/index.php on line 137, referer: http://srv-ces/centreon/main.php?
[Mon Apr 04 10:03:31 2016] [error] [client 10.29.0.118] PHP Notice:  Undefined offset: 214 in /usr/share/centreon/www/class/centreonGraph.class.php on line 1326, referer: http://srv-ces/centreon/main.php?p=20201
[Mon Apr 04 10:19:54 2016] [error] [client 10.29.0.118] PHP Warning:  strlen() expects parameter 1 to be string, array given in /usr/share/centreon/www/lib/HTML/QuickForm/checkbox.php on line 126, referer: http://srv-ces/centreon/main.php?p=60902&poller=Central
[Mon Apr 04 10:19:55 2016] [error] [client 10.29.0.118] PHP Notice:  Undefined index: autoRefresh in /usr/share/centreon/www/widgets/tactical-overview/src/hosts_status.php on line 82, referer: http://srv-ces/centreon/main.php?p=1
[Mon Apr 04 10:19:55 2016] [error] [client 10.29.0.118] PHP Notice:  Undefined index: autoRefresh in /usr/share/centreon/www/widgets/tactical-overview/src/services_status.php on line 99, referer: http://srv-ces/centreon/main.php?p=1
[Mon Apr 04 10:19:55 2016] [error] [client 10.29.0.118] PHP Notice:  Undefined index: autoRefresh in /usr/share/centreon/www/widgets/live-top10-cpu-usage/index.php on line 137, referer: http://srv-ces/centreon/main.php?p=1
[Mon Apr 04 10:21:50 2016] [error] [client 10.29.0.118] PHP Warning:  strlen() expects parameter 1 to be string, array given in /usr/share/centreon/www/lib/HTML/QuickForm/checkbox.php on line 126, referer: http://srv-ces/centreon/main.php?p=60902&poller=Central
[Mon Apr 04 10:21:51 2016] [error] [client 10.29.0.118] PHP Notice:  Undefined index: autoRefresh in /usr/share/centreon/www/widgets/live-top10-cpu-usage/index.php on line 137, referer: http://srv-ces/centreon/main.php?p=1
[Mon Apr 04 10:21:51 2016] [error] [client 10.29.0.118] PHP Notice:  Undefined index: autoRefresh in /usr/share/centreon/www/widgets/tactical-overview/src/hosts_status.php on line 82, referer: http://srv-ces/centreon/main.php?p=1
[Mon Apr 04 10:21:51 2016] [error] [client 10.29.0.118] PHP Notice:  Undefined index: autoRefresh in /usr/share/centreon/www/widgets/tactical-overview/src/services_status.php on line 99, referer: http://srv-ces/centreon/main.php?p=1
```_

**Comment by lpinsivy** [comment]
What plugin do you use to check memory ?

Can you show me the result of a check ?

**Comment by IDEAGroupe** [comment]
I use the check_centreon_memory

define by this command:
$USER1$/check_centreon_snmp_memory -H $HOSTADDRESS$ -v $_HOSTSNMPVERSION$ -C $_HOSTSNMPCOMMUNITY$ -w 80 -c 90 -S

One result for this

![image](https://cloud.githubusercontent.com/assets/18213090/14671018/fd372590-06ef-11e6-9d53-114f1987a724.png)

**Comment by SEIN-Alvaro** [comment]
Hi, just had the same problem and was about to post when I noticed I forgot to change the service description. hope it helps.

![centreon - it network monitoring - google chrome](https://cloud.githubusercontent.com/assets/24522669/21097428/aa35921c-c064-11e6-8932-f12227f7948b.jpg)

**Comment by IDEAGroupe** [comment]
unfortunately always the same thing

**Comment by Sunseeker69** [comment]
You need to look at yours metric name and service description for Memory in Centreon "Monitoring" tabs

**Comment by ytaborda17** [comment]
Hello!

I have a diferent issue, widget returns always a 0% result:

![screenshot of centreon - it network monitoring](https://user-images.githubusercontent.com/4932357/31447367-69335cb2-ae67-11e7-855f-3017a1b192c3.jpg)

What am I missing?

**Comment by ivspenna** [comment]
Still same here.
