### ISSUE TITLE
Refresh status problem

### ISSUE THREAD

**Issue by querwin** [Centreon-Widgets/centreon-widget-live-top10-memory-usage#5]
One of my service is listed on this widget as Unkown and with a percentage.

But if I look on the monitoring, I can see that this service is Unknown but did not return any percentage.

See image attached
![widget](https://cloud.githubusercontent.com/assets/7510531/14851510/b2792ea4-0c80-11e6-91f8-af2241a06170.png)
![monitoring](https://cloud.githubusercontent.com/assets/7510531/14851518/babbe8ae-0c80-11e6-99f7-c8dc53d237ab.png)

**Comment by lpinsivy** [comment]
duplicate #2
