### ISSUE TITLE
Live Top 10 Memory Usage - Filter by hostgroup does not work

### ISSUE THREAD

**Issue by lolokai** [Centreon-Widgets/centreon-widget-live-top10-memory-usage#8]
BUG REPORT INFORMATION

Centreon Web version: 2.8.4

Centreon Engine version: 1.7.0

Centreon Broker version: 3.0.2

OS: Centreon 3.4

Additional environment details (AWS, VirtualBox, physical, etc.):

Steps to reproduce the issue:

Create a Live Top 10 Memory Usage widget
Try to filter using HostGroup
Add service description and metric name
Describe the results you received:
Filter by Hostgroup doesn't work

Describe the results you expected:
Filter by Hostgroup works

Additional information you think important (e.g. issue happens only occasionally):

**Comment by lpinsivy** [comment]
fixed by 020a1aa252cba7a1326fca28c332829870862264
